# Generated by Django 4.2.2 on 2023-06-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCreationDetails',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('NameOfOrgranization', models.CharField(max_length=500)),
                ('EmailID', models.EmailField(max_length=200, unique=True)),
                ('Address', models.CharField(max_length=300)),
                ('GST', models.BigIntegerField()),
                ('AuthorisedSignatoryName', models.CharField(max_length=100)),
                ('ContactNumber', models.IntegerField()),
                ('BusinessType', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-UserId'],
            },
        ),
    ]
