# Generated by Django 4.2.2 on 2023-07-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_accountcreationdetails_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcreationdetails',
            name='ContactNumber',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='accountcreationdetails',
            name='GST',
            field=models.CharField(max_length=20),
        ),
    ]
