# Generated by Django 4.2.2 on 2023-07-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_accountcreationdetails_contactnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcreationdetails',
            name='GST',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
