# Generated by Django 4.2.2 on 2023-07-07 04:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_accountcreationdetails_gst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcreationdetails',
            name='GST',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
