# Generated by Django 4.2.2 on 2023-07-10 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_accountcreationdetails_gst'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('machine_type', models.CharField(max_length=100)),
                ('name_of_machine', models.CharField(max_length=100)),
                ('machine_manufacturer', models.CharField(max_length=100)),
                ('machine_model_number', models.CharField(max_length=100)),
                ('machine_build_date', models.DateField()),
                ('machine_condition', models.CharField(max_length=100)),
                ('machine_dimension', models.CharField(max_length=100)),
                ('machine_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location_of_machine', models.CharField(max_length=100)),
                ('machine_image_1', models.ImageField(upload_to='media/')),
                ('machine_image_2', models.ImageField(upload_to='media/')),
                ('machine_image_3', models.ImageField(upload_to='media/')),
                ('machine_image_4', models.ImageField(blank=True, upload_to='media/')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.accountcreationdetails')),
            ],
            options={
                'ordering': ['-product_id'],
            },
        ),
    ]
