# Generated by Django 4.2.2 on 2023-07-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_productdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='machine_image_2',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='machine_image_3',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
