# Generated by Django 4.2.2 on 2023-08-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_productdetails_machine_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcreationdetails',
            name='GST',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='accountcreationdetails',
            name='Password',
            field=models.CharField(max_length=100),
        ),
    ]
